### PR TITLE
Bump to 1.0.0-prerelease.1

### PR DESCRIPTION
**Pull request by ghost**
Update to the latest version of beaker.

### CODE REVIEW

**Comment by ghost** [comment]
Ran into this one issue.
```
[116:0514/220341.953356:FATAL:platform_shared_memory_region_posix.cc(254)] This is frequently caused by incorrect permissions on /dev/shm.  Try 'sudo chmod 1777 /dev/shm' to fix.
```
Application launches with missing graphics and then hangs. Granting permission to shm will not fix, and wouldn't be an optimal situation in any case.

**Comment by ghost** [comment]
Fuse related issues, wayland also not working.

**Comment by G-Ray** [comment]
Thank you @MrSenshi . I don't know if fuse can work with flatpak. Do you have any clue about what could be the cause of these blank windows ?

**Comment by da2x** [comment]
1.0.0-prerelease.2 is out now (a.k.a. beta1).

**Comment by da2x** [comment]
@MrSenshi, `node` is missing from the AppImage. That’s why the Hyperspace daemon isn’t starting. Add the following to the manifest:

```
sdk: org.freedesktop.Sdk
sdk-extensions:
  - org.freedesktop.Sdk.Extension.node14
[…]
modules:
  - name: nodejs
    buildsystem: simple
    build-commands:
      - install -Dm 755 /usr/lib/sdk/node14/bin/node /app/bin/node
```

**Comment by da2x** [comment]
1.0 stable is out, so you can update to:

```
        url: https://github.com/beakerbrowser/beaker/releases/download/1.0.0/Beaker.Browser-1.0.0.AppImage
        sha256: b34a0c98d70d85f3ae14418a204e25aa30a5ae9e1e2209fb1930fdcdf847f438
```

**Comment by da2x** [comment]
Lastly, there’s an unresolved problem with the Electron renderer crashing when it fails to open a shared memory region. It [originates with Chromium](https://chromium.googlesource.com/chromium/src/+/7b882500303dd0c9a416dc6330530de02e76f2b7/base/memory/platform_shared_memory_region_posix.cc#190). You can see it when you run `flatpak run --env=ELECTRON_ENABLE_LOGGING=1 com.beakerbrowser.Beaker`.

```
[ERROR:platform_shared_memory_region_posix.cc(250)] Creating shared memory in /dev/shm/.org.chromium.Chromium.J6LDq2 failed: Operation not permitted (1)
[ERROR:platform_shared_memory_region_posix.cc(253)] Unable to access(W_OK|X_OK) /dev/shm: Operation not permitted (1)
[FATAL:platform_shared_memory_region_posix.cc(255)] This is frequently caused by incorrect permissions on /dev/shm.  Try 'sudo chmod 1777 /dev/shm' to fix
```

Neither adding `--disable-dev-shm-usage` to the exec command or `--device=shm` to the finish arguments resolves this problem. I’m not sure what’s going on with this one.

**Pull request closed without merging**
